### ISSUE TITLE
general experience, ideas, and thank you

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [sinic/ednc#2]
I am wont to browse old Sacha Chua emacs news post for tid-bits I may have
missed the first time I saw them. Had I not done this, I would probably have not
seen this package--and even then when I saw this package's name `ednc - Emacs
Desktop Notification Center` I almost skipped it because I had a vague idea of
what it was. Luckily, I didn't. When I actually realized what this package did
my interest quickly rose. Just a few days ago I had installed dunst and I had
been dreading having to figure out its configuration language. Because of this
package, I can throw that package out of the window _with gusto_.

I am still experimenting with this package trying to figure out how to best
display notifications. The example you gave on popping notification buffers was
useful, however I don't think I will adopt this approach because I want
notifications to show up in a small box (probably on the right-hand corner) and
I don't see how you can get a buffer there in a layout that has few splits (at
least without creating many buffer splits). I want something like a floating
window just as popups typically show up. I thought I could either use a frame or
a posframe. Since I use exwm and as per my experiments it does not seem frames
stack in exwm (though I could be wrong, I'll ask about this), I tried postframe.

This is the test I've done so far based on your example. Of course I need to
change `:position` so it's not always at point--I'll see how `ivy-posframe` does
that. It seems promising, though I would want a different themes for the
posframe (based on severity of the notification) so I checked out [color-theme-buffer-local](https://github.com/vic/color-theme-buffer-local) after reading [this stackexchange post](https://emacs.stackexchange.com/questions/3622/use-a-different-color-theme-for-eww-buffers).

```elisp
(defun show-posframe-in-buffer (old new)
  (let ((name (format "Notification %d" (ednc-notification-id (or old new)))))
    (with-current-buffer (get-buffer-create name)
      (if new (let ((inhibit-read-only t))
                (if old (erase-buffer) (ednc-view-mode))
                (insert (ednc-format-notification new t))
                (when (posframe-workable-p)
                  (posframe-show name :position (point))))
        (kill-buffer)))))

(add-hook 'ednc-notification-presentation-functions #'show-posframe-in-buffer)

(notifications-notify :title "ho" :body "hello world my name is bob" :urgency 'critical)
;; use (posframe-hide-all) to get rid of the posframe
```
This needs much more work to be acceptable, but I'm happy with the start.

I want to propose to add a simple example on how to actually see a notification happening. Not so familiar with notifications, I struggled with that at first when I was trying to figure out how this package works. The `test` file is what got me to see that you trigger notifications via `notifications-notify`.

Thank you for writing such an amazing package.

**Comment by sinic** [comment]
Thanks for your feedback! Judging by the GitHub stats, the mention by Sacha Chua is responsible for most of the recent interest in this package. Since you mentioned EXWM, I think of most of its users as potential users of EDNC as well, but they are hard to reach without spamming the project at places specific to EXWM. Seems I have to rely on word of mouth here.

> Since I use exwm and as per my experiments it does not seem frames stack in exwm (though I could be wrong, I'll ask about this), I tried postframe.

This appears [not to be possible in EXWM](https://github.com/ch11ng/exwm/issues/560), unfortunately. One can get pretty close to what I think you want without using external packages. With the following function, an appropriately sized window should almost always appear at the bottom (though not at the bottom right) of the frame, and disappear once the notification is closed:
```elisp
(defun show-notification-in-buffer (old new)
  (let ((name (format "Notification %d" (ednc-notification-id (or old new)))))
    (with-current-buffer (get-buffer-create name)
      (if new (let ((inhibit-read-only t))
                (if old (erase-buffer) (ednc-view-mode))
                (save-excursion (insert (ednc-format-notification new t)))
                (pop-to-buffer (current-buffer)
                               (cons #'display-buffer-at-bottom
                                     '((window-height . fit-window-to-buffer)
                                       (dedicated . t)))))
        (kill-buffer)))))
```

I deliberately kept the functions in the README as minimal as possible, though, to encourage users to build their personal solution on top of EDNC, as that will be superior to anything I could possibly come up with. Nothing wrong with relying on external packages like posframe either!

> I want to propose to add a simple example on how to actually see a notification happening.

Done. Unfortunately the `notifications` library makes it a little too easy to create notifications that are in violation of the standard (e.g., by missing a default action).
